
import {
    PageSection,
    ListContainer,
    ListItem,
    SubListContainer,
    SectionHeader
} from '../styledComponents';

const Experience = () => {
    return (
        <PageSection id="experience">
            <SectionHeader>Experiences</SectionHeader>
            <ListContainer>
                <ListItem>
                    <b>AI Model Trainer - DataAnnotation</b><br />
                    March 2024 - Present <br />
                    <SubListContainer>
                        <ListItem>
                            Conducted in-depth conversations with AI models on diverse coding topics, including data manipulation, file generation, code generation, and error checking, primarily focusing on Python.
                        </ListItem>
                        <ListItem>
                            Critically analyzed and rectified incorrect code, data, and information generated by AI models, enhancing overall model accuracy and reliability.
                        </ListItem>
                        <ListItem>
                            Implemented rigorous quality assurance protocols to ensure the integrity of AI-generated code and data.
                        </ListItem>
                        <ListItem>
                            Authored detailed reports on model performance, highlighting areas for improvement and suggesting optimization strategies.
                        </ListItem>
                    </SubListContainer>
                </ListItem>
                <ListItem>
                    <b>IT Support - Quincy College</b><br />
                    July 2023 - August 2023 <br />
                    <SubListContainer>
                        <ListItem>
                            Efficiently installed, configured, upgraded, and troubleshoot hardware, software applications, operating systems, and network protocols to maintain optimal IT infrastructure.
                        </ListItem>
                        <ListItem>
                            Provided prompt and effective technical support to customers and internal users, resolving complex issues and ensuring minimal downtime.
                        </ListItem>
                        <ListItem>
                            Proactively identified system malfunctions and performance issues, implementing timely solutions to prevent service disruptions.
                        </ListItem>
                        <ListItem>
                            Collaborated closely with internal teams to deliver accurate and timely information to customers, enhancing service quality and account management.
                        </ListItem>
                    </SubListContainer>
                </ListItem>
                <ListItem>
                    <b>Office Assistant</b><br />
                    June 2021 - August 2022 <br />
                    <SubListContainer>
                        <ListItem>
                            Served as the first point of contact for visitors, efficiently assessing their needs and directing them to appropriate personnel, enhancing overall office productivity.
                        </ListItem>
                        <ListItem>
                            Orchestrated office operations by effectively managing deliveries, organizing supplies, and maintaining a well-structured work environment.
                        </ListItem>
                    </SubListContainer>
                </ListItem>
            </ListContainer>
        </PageSection>
    );
};

export default Experience;